[project]
repository-type = "library"
versioning-scheme = "library"
branching-model = "library-release"
release-model = "artifact-publishing"
[ci]
versions = ["latest"]
integration-tests = false

[publish]
release = true
docs = true

[dependencies]
vergil = "v2.1"
